name: Spring Boot CD

on:
  workflow_run:
    workflows: ["Spring Boot CI with Gradle"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connect ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: ls -al

    - name: Deploy
      run: |
        sudo sh deploy.sh